# Generated by Django 5.0.1 on 2024-02-02 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('idDctor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreDoctor', models.CharField(max_length=50, verbose_name='Nombre')),
                ('especialidad', models.CharField(max_length=50, verbose_name='Escpecialidad')),
                ('grado_cientifico', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Máster', 'Máster'), ('Doctor', 'Doctor')], max_length=10, verbose_name='Grado científico')),
                ('ciDoctor', models.CharField(max_length=50, verbose_name='CI')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombrePaciente', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ciPaciente', models.CharField(max_length=50, verbose_name='CI')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('phoneNumber', models.IntegerField(max_length=10, verbose_name='Numeo de telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('idSala', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('piso', models.IntegerField(verbose_name='Piso')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.doctor')),
            ],
        ),
    ]
