# Generated by Django 5.0.1 on 2024-02-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='grado_cientifico',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Máster', 'Máster'), ('Ninguno', 'Ninguno')], max_length=10, verbose_name='Grado científico'),
        ),
    ]
