# Generated by Django 5.0.1 on 2024-02-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0009_alter_doctor_grado_cientifico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='grado_cientifico',
            field=models.CharField(choices=[('Máster', 'Máster'), ('Ninguno', 'Ninguno'), ('Doctor', 'Doctor')], max_length=10, verbose_name='Grado científico'),
        ),
    ]
