# Generated by Django 5.0.1 on 2024-02-08 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0011_alter_paciente_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='idDctor',
            new_name='id_doctor',
        ),
    ]
