# Generated by Django 5.0.1 on 2024-02-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0012_rename_iddctor_doctor_id_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='grado_cientifico',
            field=models.CharField(choices=[('Máster', 'Máster'), ('Doctor', 'Doctor'), ('Ninguno', 'Ninguno')], max_length=10, verbose_name='Grado científico'),
        ),
    ]
