# Generated by Django 5.0.1 on 2024-02-08 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0014_alter_doctor_grado_cientifico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idEspecial', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la especialidad')),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='grado_cientifico',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Ninguno', 'Ninguno'), ('Máster', 'Máster')], max_length=10, verbose_name='Grado científico'),
        ),
        migrations.CreateModel(
            name='RegistroDPaciente',
            fields=[
                ('idRegistroPaciente', models.BigAutoField(primary_key=True, serialize=False)),
                ('enfermedad', models.CharField(max_length=50, verbose_name='Enfermedad')),
                ('paciente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.paciente')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.sala')),
            ],
        ),
    ]
