# Generated by Django 5.0.1 on 2024-02-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0015_especialidad_alter_doctor_grado_cientifico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='grado_cientifico',
            field=models.CharField(choices=[('Máster', 'Máster'), ('Ninguno', 'Ninguno'), ('Doctor', 'Doctor')], max_length=10, verbose_name='Grado científico'),
        ),
    ]
