# Generated by Django 5.0.1 on 2024-02-08 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0016_alter_doctor_grado_cientifico'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodpaciente',
            name='doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='HospitalApp.doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='grado_cientifico',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Ninguno', 'Ninguno'), ('Máster', 'Máster')], max_length=10, verbose_name='Grado científico'),
        ),
    ]
